package com.example.bei_i_bei.everywheretrip.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bei_i_bei.everywheretrip.bean.FocusBean;

import com.example.bei_i_bei.everywheretrip.dao.FocusBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig focusBeanDaoConfig;

    private final FocusBeanDao focusBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        focusBeanDaoConfig = daoConfigMap.get(FocusBeanDao.class).clone();
        focusBeanDaoConfig.initIdentityScope(type);

        focusBeanDao = new FocusBeanDao(focusBeanDaoConfig, this);

        registerDao(FocusBean.class, focusBeanDao);
    }
    
    public void clear() {
        focusBeanDaoConfig.clearIdentityScope();
    }

    public FocusBeanDao getFocusBeanDao() {
        return focusBeanDao;
    }

}
